/**
 * Fallback cartoon illustrations when a topic has no imageUrl saved yet.
 * Keyed by module code ? topic sortOrder (1-based).
 */
const introTopicImages: Record<number, string[]> = {
  1: ['/images/training/gateway/whs-responsibilities.png'],
  2: ['/images/training/gateway/risk-management.png'],
  3: ['/images/training/gateway/issue-resolution.png'],
  4: ['/images/training/gateway/your-responsibility.png'],
  5: ['/images/training/gateway/workplace-hazards.png'],
  6: ['/images/training/gateway/manual-handling-awareness.png'],
  7: ['/images/training/gateway/safe-lifting.png'],
  8: ['/images/training/gateway/ergonomics.png'],
  9: ['/images/training/gateway/workplace-stress.png'],
  10: ['/images/training/gateway/stress-tips.png'],
  11: ['/images/training/gateway/discrimination.png'],
  12: ['/images/training/gateway/discrimination-law.png'],
  13: ['/images/training/gateway/sexual-harassment.png'],
  14: ['/images/training/gateway/sexual-harassment-law.png'],
  15: ['/images/training/gateway/workplace-harassment.png'],
  16: ['/images/training/gateway/respond-harassment.png'],
  17: ['/images/training/gateway/bullying.png'],
  18: ['/images/training/gateway/not-bullying.png'],
  19: ['/images/training/gateway/module-complete.png'],
};

export const TRAINING_TOPIC_IMAGES: Record<string, Record<number, string[]>> = {
  SL: introTopicImages,
  GATEWAY: introTopicImages,
  M1: {
    1: ['/images/training/themes/welcome.png'],
    2: ['/images/training/themes/office-hazards.png'],
    3: ['/images/training/themes/office-housekeeping.png'],
    4: ['/images/training/themes/office-equipment.png'],
    5: ['/images/training/themes/electrical-safety.png'],
    6: ['/images/training/themes/faulty-electrical-equipment.png'],
    7: ['/images/training/themes/slips-trips.png'],
    8: ['/images/training/themes/office-chemicals.png'],
    9: ['/images/training/themes/office-lifting.png'],
    10: ['/images/training/themes/office-lifting.png'],
    11: ['/images/training/gateway/ergonomics.png'],
    12: ['/images/training/themes/rest-breaks.png'],
    13: ['/images/training/gateway/ergonomics.png'],
    14: ['/images/training/gateway/ergonomics.png'],
    15: ['/images/training/gateway/ergonomics.png'],
    16: ['/images/training/gateway/ergonomics.png'],
    17: ['/images/training/gateway/ergonomics.png'],
    18: ['/images/training/themes/emergency.png'],
    19: ['/images/training/themes/aggression.png'],
    20: ['/images/training/themes/first-aid.png'],
    21: ['/images/training/gateway/workplace-stress.png'],
    22: ['/images/training/gateway/workplace-stress.png'],
    23: ['/images/training/gateway/workplace-stress.png'],
    24: ['/images/training/gateway/stress-tips.png'],
    25: ['/images/training/gateway/stress-tips.png'],
    26: ['/images/training/themes/slips-trips.png'],
    27: ['/images/training/themes/office-carpark.png'],
    28: ['/images/training/gateway/module-complete.png'],
  },
  M3: {
    1: ['/images/training/themes/forklift-welcome.png'],
    2: ['/images/training/themes/forklift-training.jpg'],
    3: ['/images/training/themes/forklift-hazards.jpg'],
    4: ['/images/training/themes/forklift-operating.jpg'],
    5: ['/images/training/themes/forklift-parking.jpg'],
    6: ['/images/training/themes/forklift-instability.jpg'],
  },
  MANUAL: {
    1: ['/images/training/gateway/manual-handling-awareness.png'],
    2: ['/images/training/themes/welcome.png'],
    3: ['/images/training/gateway/workplace-hazards.png'],
    4: ['/images/training/themes/mh-risk-assess.png'],
    5: ['/images/training/themes/mh-self-check.png'],
    6: ['/images/training/themes/mh-work-practices.png'],
    7: ['/images/training/themes/mh-equipment-fault.png'],
    8: ['/images/training/themes/mh-environment-hazards.png'],
    9: ['/images/training/themes/mh-product-awkward.png'],
    10: ['/images/training/themes/mh-risk-assess.png'],
    11: ['/images/training/gateway/whs-responsibilities.png'],
    12: ['/images/training/themes/injury.png'],
    13: ['/images/training/manual/spine-curves.png'],
    14: ['/images/training/themes/awkward-posture.png'],
    15: ['/images/training/manual/body-toolbox.png'],
    16: ['/images/training/themes/mh-principles-lift.png'],
    17: ['/images/training/themes/mh-stable-base.png'],
    18: ['/images/training/themes/mh-face-load-close.png'],
    19: ['/images/training/themes/mh-practical-equal-lift.png'],
    20: ['/images/training/themes/mh-stretching.png'],
    21: ['/images/training/gateway/module-complete.png'],
  },
};

const theme = (file: string) => `/images/training/themes/${file}`;
const gateway = (file: string) => `/images/training/gateway/${file}`;

/** Most specific subject first. Shared cartoons are reused when the topic is the same. */
const TOPIC_CARTOONS: { test: RegExp; src: string }[] = [
  { test: /cpr|bls/i, src: theme('cpr.png') },
  { test: /code brown/i, src: theme('code-brown.png') },
  { test: /extinguisher/i, src: theme('fire-extinguisher.png') },
  { test: /asbestos/i, src: theme('asbestos.png') },
  { test: /confined/i, src: theme('confined-space.png') },
  { test: /permit work|entry permit/i, src: theme('confined-space.png') },
  { test: /residual current|\brcd\b/i, src: theme('rcd.png') },
  { test: /mower/i, src: theme('mower.png') },
  { test: /power tool/i, src: theme('power-tools.png') },
  { test: /licen[cs]e/i, src: theme('licence.png') },
  { test: /elevating work|\bewp\b/i, src: theme('ewp.png') },
  { test: /fall arrest|travel restraint|work positioning|harness/i, src: theme('harness.png') },
  { test: /scaffold/i, src: theme('scaffold.png') },
  { test: /roof-heights|roof and gutter|working on the (roof|gutter)/i, src: theme('roof-heights-blower.png') },
  { test: /perimeter guard|working at height|falls from|fall risk/i, src: theme('working-at-heights.png') },
  { test: /ladder/i, src: theme('ladder.png') },
  { test: /faulty electrical|identifying faulty|cracked.*socket|heat damage/i, src: theme('faulty-electrical-equipment.png') },
  { test: /electrical line|power line/i, src: theme('power-lines.png') },
  { test: /load handling|attachments|work platform/i, src: theme('forklift-load.png') },
  { test: /forklift|ramps|loading dock|operation fundamental|parking|out of service/i, src: theme('forklift.png') },
  { test: /ventilation/i, src: theme('ventilation.png') },
  { test: /pedestrian|traffic/i, src: theme('traffic.png') },
  { test: /mobile plant/i, src: theme('mobile-plant.png') },
  { test: /loading & unloading|loading and unloading/i, src: theme('traffic.png') },
  { test: /spill/i, src: theme('spill.png') },
  { test: /dangerous good|placard|segregation|transfer of dg/i, src: theme('dangerous-goods.png') },
  { test: /signage/i, src: theme('signage.png') },
  { test: /sun|\buv\b|skin protection/i, src: theme('sun-protection.png') },
  { test: /respiratory|\bppe\b|personal protective/i, src: theme('ppe.png') },
  { test: /acoustic|headset|voice fatigue/i, src: theme('acoustic.png') },
  { test: /call centre/i, src: theme('call-centre.png') },
  { test: /how to respond/i, src: gateway('respond-harassment.png') },
  { test: /sexual harassment and the law/i, src: gateway('sexual-harassment-law.png') },
  { test: /sexual harassment/i, src: gateway('sexual-harassment.png') },
  { test: /discrimination and the law/i, src: gateway('discrimination-law.png') },
  { test: /discrimination|diverse workforce|racial or ethnic/i, src: gateway('discrimination.png') },
  { test: /victimisation|victimization/i, src: gateway('victimisation.png') },
  { test: /not bullying|reasonable management/i, src: gateway('not-bullying.png') },
  { test: /bullying/i, src: gateway('bullying.png') },
  { test: /harassment/i, src: gateway('workplace-harassment.png') },
  { test: /tips for dealing|identifying & managing stress|identifying and managing stress/i, src: gateway('stress-tips.png') },
  { test: /stress/i, src: gateway('workplace-stress.png') },
  { test: /workplace environment|cluttered or a small/i, src: theme('mh-environment-hazards.png') },
  { test: /you as the worker/i, src: theme('mh-self-check.png') },
  { test: /work practices/i, src: theme('mh-work-practices.png') },
  { test: /equipment hazards/i, src: theme('mh-equipment-fault.png') },
  { test: /load or product/i, src: theme('mh-product-awkward.png') },
  { test: /sources of manual handling/i, src: theme('mh-risk-assess.png') },
  { test: /postures and tasks to avoid|awkward posture|work postures to avoid/i, src: theme('awkward-posture.png') },
  { test: /key manual handling principles/i, src: theme('mh-principles-lift.png') },
  { test: /stable base|maintain curves|natural curves/i, src: theme('mh-stable-base.png') },
  { test: /power, load close|face the task|keep the load close/i, src: theme('mh-face-load-close.png') },
  { test: /practical application|practical techniques|pushing and pulling/i, src: theme('mh-practical-equal-lift.png') },
  { test: /^risk management$/i, src: theme('mh-risk-assess.png') },
  { test: /risk control/i, src: theme('mh-risk-control.png') },
  { test: /monitor and review/i, src: theme('mh-monitor-review.png') },
  { test: /risk assessment/i, src: theme('mh-risk-assess.png') },
  { test: /body is your toolbox/i, src: '/images/training/manual/body-toolbox.png' },
  { test: /spine/i, src: theme('spine-curves-lift.png') },
  { test: /safe lifting/i, src: gateway('safe-lifting.png') },
  { test: /manual task|manual handling|hazardous manual/i, src: gateway('manual-handling-awareness.png') },
  { test: /ergonomic|workstation|work station|chair|keyboard|mouse|computer screen|under desk|storage on top|occupational overuse|\bmsd\b|hot desk/i, src: gateway('ergonomics.png') },
  { test: /rest break|task variety/i, src: theme('rest-breaks.png') },
  { test: /slip|trip/i, src: theme('slips-trips.png') },
  { test: /^\s*falls\b/i, src: theme('working-at-heights.png') },
  { test: /faulty electrical|identifying faulty|cracked.*socket|heat damage/i, src: theme('faulty-electrical-equipment.png') },
  { test: /electrical/i, src: theme('electrical-safety.png') },
  { test: /chemical|hazardous substance|msds|\bsds\b/i, src: theme('chemicals-sds.png') },
  { test: /house\s*keeping/i, src: theme('housekeeping.png') },
  { test: /first aid/i, src: theme('first-aid.png') },
  { test: /injur/i, src: theme('injury.png') },
  { test: /fatigue/i, src: theme('fatigue.png') },
  { test: /burn|scald/i, src: theme('burns.png') },
  { test: /sharp|biological/i, src: theme('sharps.png') },
  { test: /nursing|health worker/i, src: theme('nursing.png') },
  { test: /outdoor/i, src: theme('sun-protection.png') },
  { test: /access and security|working alone/i, src: theme('working-alone.png') },
  { test: /aggression|violence|threat/i, src: theme('aggression.png') },
  { test: /isolated|remote|check-in/i, src: theme('working-alone.png') },
  { test: /issue resolution|raising issues|unsafe work|responding to safety/i, src: gateway('issue-resolution.png') },
  { test: /your responsibility|your duty|employer/i, src: gateway('your-responsibility.png') },
  { test: /typical hazards|office hazard/i, src: theme('office-hazards.png') },
  { test: /^equipment$/i, src: theme('office-equipment.png') },
  { test: /travel and the vehicle/i, src: theme('vehicle-load-safety.png') },
  { test: /risk/i, src: gateway('risk-management.png') },
  { test: /hazard/i, src: gateway('workplace-hazards.png') },
  { test: /whs|consultation|responsibilit|on-hire|host organisation/i, src: gateway('whs-responsibilities.png') },
  { test: /storage/i, src: theme('storage.png') },
  { test: /operating equipment|\bequipment\b/i, src: theme('power-tools.png') },
  { test: /emergency/i, src: theme('emergency.png') },
  { test: /incident|occurrence|reporting/i, src: theme('incident-report.png') },
  { test: /training & supervision|information, instruction|instruction, training/i, src: theme('welcome.png') },
  { test: /completion|summary/i, src: gateway('module-complete.png') },
  { test: /welcome|introduction|learning outcome|overview|starting your new role|ict worker/i, src: theme('welcome.png') },
];

export function cartoonForTopicTitle(title?: string | null): string | null {
  const text = String(title || '').replace(/\s+/g, ' ').trim();
  if (!text) return null;
  const hit = TOPIC_CARTOONS.find((row) => row.test.test(text));
  return hit?.src || theme('welcome.png');
}

export function topicImagesFor(
  moduleCode: string | null | undefined,
  sortOrder: number,
  imageUrl?: string | null,
  title?: string | null,
): string[] {
  const fromTopic = String(imageUrl || '').trim();
  if (fromTopic) return [fromTopic];
  const code = String(moduleCode || '').trim().toUpperCase();
  const mapped = code && sortOrder ? TRAINING_TOPIC_IMAGES[code]?.[sortOrder] : undefined;
  if (mapped?.length) return mapped;
  const themed = cartoonForTopicTitle(title);
  return themed ? [themed] : [];
}
