export type ToolboxSeed = {
  code: string;
  title: string;
  durationMins: number;
  sortOrder: number;
  brief: string;
  points: string[];
  imageUrl: string;
};

const img = (file: string) => `/images/training/themes/${file}`;
const gateway = (file: string) => `/images/training/gateway/${file}`;

export const TOOLBOX_SEEDS: ToolboxSeed[] = [
  {
    code: 'SLIPS',
    title: 'Slips, trips and falls',
    durationMins: 15,
    sortOrder: 1,
    imageUrl: img('slips-trips.png'),
    brief: 'Most injuries on cleaning and grounds work happen at floor level. A wet floor, a hose, a loose mat or a broken drain cover is enough to put someone in hospital. This talk is about falls on the same level, not work on a roof.\n\nCauses on our work\nWet floors after mopping, rain on entries, and moss on paths. Leads, hoses and blower cords across walkways. Uneven pavers, lifted drain covers, and tools left where the next person walks. Poor light in plant rooms, car parks and amenities. Walking backwards while you look at a machine instead of the ground.\n\nBefore you start\nWalk the path you will use, including the way back to the vehicle. Look for water, leaves, oil, broken tiles and missing covers. If you cannot see the ground, get a light or wait. Tell your supervisor about a broken cover, a missing rail or a light that is out. Do not step over it and leave it for the next crew.\n\nDuring the job\nKeep leads and hoses along the edge of the walkway, not across it. Use the shortest lead that reaches. Put a wet-floor sign out before the floor is wet, and leave it there until the floor is dry, not until you have finished the room. Keep people off the wet area. Wear the boots you have been issued. Smooth shoes and thongs are not grip.\n\nCarry only what you can see over. A tall stack of bins blocks the ground in front of you. If you must walk backwards with a machine, stop and check the ground first.\n\nWhen to stop\nStop if the surface is icy, oily, or covered in moss and you have no safe way across. Stop if a drain cover rocks or a step has collapsed. Do not test it with your weight. A near slip is reported the same day, because the next person may not be as lucky.',
    points: [
      'What slip or trip hazards are on this site today?',
      'Where will wet-floor signs go, and when will they come down?',
      'Where are leads and hoses likely to cross a walkway?',
      'Which boots are you wearing, and is the sole still gripping?',
      'Who do you tell if a path, drain cover or light is broken?',
    ],
  },
  {
    code: 'FIRE',
    title: 'Fire safety',
    durationMins: 15,
    sortOrder: 2,
    imageUrl: img('fire-extinguisher.png'),
    brief: 'You need to know how to get out of this site before you need to. A fire in a plant room, a bin room or a vehicle does not leave time to look for the exit.\n\nBefore you start\nFind two ways out, not only the door you came in. Find the assembly point. Find how the alarm is raised: a break-glass point, a shout, or a phone call to the site contact. Check that bins, plant and cords are not blocking an exit or a hose reel. If they are, move them and tell your supervisor.\n\nWhat starts fires on our work\nChargers left on bedding, paper or chemicals. Fuel stored near a hot motor or a spark. A blower or mower refuelled while it is hot. Oily rags in a closed bin. Damaged leads. Smoking where it is banned, including near fuels and in amenities.\n\nIf you see smoke or fire\nWarn the people near you and raise the alarm. Leave by the nearest safe exit. Close doors behind you if you can do that without delay. Go to the assembly point and stay there so someone can count the crew. Call 000. Do not go back for tools or a vehicle.\n\nUsing an extinguisher\nA fire extinguisher is only for a small fire, and only if you have been shown that type of extinguisher, the fire is not between you and the exit, and you can put it out in seconds. If you are not sure, leave. Water on an electrical fire or on fuel makes it worse. The label on the extinguisher tells you what it is for. If the extinguisher is missing, discharged or blocked, report it the same day.\n\nAfter you are out\nTell your supervisor who is accounted for and who is not. Leave the scene as it is unless you must help someone. Do not restart work until you are told the site is safe.',
    points: [
      'Where are the two nearest exits and the assembly point?',
      'How is the alarm raised on this site?',
      'Is any exit, hose reel or extinguisher blocked or missing?',
      'What would you do if you saw smoke in a plant room?',
      'Which fire would you leave rather than fight?',
    ],
  },
  {
    code: 'FATIGUE',
    title: 'Fatigue',
    durationMins: 15,
    sortOrder: 3,
    imageUrl: img('fatigue.png'),
    brief: 'Fatigue is a safety hazard. It slows your reactions, your judgement and your driving. It shows up on early starts, long shifts, hot days, and after poor sleep. Working alone makes it easier to ignore.\n\nHow it shows up\nHeavy eyes, yawning, drifting thoughts, missing a turn, irritability, and doing a task you have done a hundred times and still getting it wrong. On the road it looks like wandering in the lane or not remembering the last few minutes. Those are signs to stop, not signs to push through.\n\nWhat the job requires\nUse the breaks in the roster. A break in the vehicle with the phone in your hand is not rest. Eat and drink. Heat and dehydration make fatigue worse, especially on mowing and roof work in summer.\n\nSay no to extra hours when you are already too tired to work safely. Helping the crew finish is not a reason to drive impaired by tiredness. If the last site ran late, the next site can be told. Call your supervisor and reset the plan.\n\nDriving\nIf you are too tired to drive, say so before you leave the site. Swap the driving if someone else is fit. If nobody is fit, stop. A short sleep in a safe place and a call to your supervisor is the control. Coffee is not a control.\n\nWhat you report\nTell your supervisor if the roster, the travel or the heat is making the crew unsafe. A near miss caused by tiredness is reported the same day. Do not wait for a crash.',
    points: [
      'What signs of fatigue have you noticed on this job?',
      'When are the planned breaks today, and where will you take them?',
      'What do you do if the last site runs late and you are due on the road?',
      'What do you do if you are too tired to drive to the next site?',
      'How does heat on this site change the plan?',
    ],
  },
  {
    code: 'ALCOHOL',
    title: 'Drugs and alcohol',
    durationMins: 15,
    sortOrder: 4,
    imageUrl: img('fitness-for-work.png'),
    brief: 'You must be fit for work before you drive, climb, or use plant. Alcohol, illegal drugs, and some prescribed or pharmacy medicines affect balance, reaction time and judgement. The effect can still be there the next morning.\n\nFit for work\nFit for work means you can do the job without putting yourself or anyone else at risk. If you are unsure, you are not fit. Do not start the shift and hope it wears off. Tell your supervisor before you leave home or before you take the keys.\n\nMedicines\nRead the warning on prescribed and pharmacy medicines. If it says the medicine may cause drowsiness, or says do not drive or operate machinery, tell your supervisor. A medicine you are allowed to take can still make you unfit for a roof, a mower or a vehicle. Do not share medicines.\n\nOther people\nDo not cover for someone who is unfit. Do not let them drive the crew. Speak to your supervisor. This is about stopping an injury, not about punishment. If someone is aggressive or collapsing, keep your distance, get help, and call 000 if they need urgent care.\n\nAlcohol and drugs at work\nDo not drink alcohol or use illegal drugs at work, in a work vehicle, or on a site. Do not keep them in the vehicle. An incident that involves alcohol or drugs is reported the same day, including a near miss.\n\nIf you need help\nYou can tell your supervisor that you need support. Asking for help before an incident is the safe path.',
    points: [
      'What does fit for work mean before you drive or use plant?',
      'What should you do if a medicine makes you drowsy?',
      'What do you do if you are still affected the morning after?',
      'Who do you tell if you think someone is not fit for work?',
      'What is not allowed in a work vehicle?',
    ],
  },
  {
    code: 'ILLNESS',
    title: 'Cold and flu',
    durationMins: 15,
    sortOrder: 5,
    imageUrl: img('first-aid.png'),
    brief: 'A cold or flu spreads in shared vehicles, lunch rooms and amenities. Coming to work sick does not help the crew. It takes other people off the job next week, and it puts clients and the public at risk.\n\nWhen you stay home\nStay home if you have a fever, if you are too unwell to work safely, or if you have been told to isolate. Drowsy cold-and-flu tablets and a shift on a ladder or a mower do not mix. If you wake up too sick to work, call your supervisor early so the shift can be covered. A text after the crew has already left is too late.\n\nHow it spreads on our work\nHands on steering wheels, door handles, fuel cards and shared tools. Drink bottles left in the console. Coughing in a closed vehicle. Cleaning amenities and then eating without washing your hands.\n\nWhat you do\nCover coughs. Wash your hands with soap and water before you eat and after you clean. Do not share drink bottles or towels. Wipe shared vehicle controls and door handles as you have been shown. Keep a sick person out of a crowded vehicle if they have come to work by mistake. Send them home.\n\nWork that can wait\nIf you are mildly unwell and you have been cleared to work, do not take the jobs that need a clear head: roofs, traffic, chemicals, or driving the crew. Tell your supervisor and take the lower-risk work.\n\nWhat you report\nTell your supervisor the same day if several people on the crew are sick. That is a workplace issue, not a private one.',
    points: [
      'When should you stay home instead of starting a shift?',
      'Who do you call if you wake up too unwell to work?',
      'Which shared surfaces on this job need cleaning?',
      'Which jobs today should not be done by someone who is unwell?',
      'What do you do if a workmate turns up sick?',
    ],
  },
  {
    code: 'INFECTION',
    title: 'Infectious diseases',
    durationMins: 15,
    sortOrder: 6,
    imageUrl: img('sharps.png'),
    brief: 'Cleaning toilets, kitchens, amenities and public areas exposes you to infection. Body fluids, used sharps and unknown waste are treated as hazardous even when they look dry.\n\nWhat you treat as hazardous\nBlood, vomit, faeces and urine. Needles and other sharps in gardens, car parks, toilets and bins. Nappies and sanitary waste. Unknown powders or liquids. A bin that smells of chemicals. Do not sort through a bin with bare hands to see what is in it.\n\nProtection\nWear the gloves you have been given, and eye protection if there is a splash risk. Cover cuts before you start. Change gloves between a toilet and a food area. Wash your hands before you eat, even if you wore gloves. Gloves are not a substitute for washing.\n\nSharps\nDo not pick up a needle by hand. Do not kick it, snap it, or put it in a clothing bin or a rubbish bag. Use the sharps container and the method you have been shown. If you have not been given that method, leave the sharp, keep people away, and call your supervisor.\n\nIf you are exposed\nIf you are splashed in the eyes, mouth or an open cut, wash the area straight away with running water. Do not scrub. Tell your supervisor the same day and get medical advice. A needle stick is reported immediately. Know where the first aid kit and the nearest water are before you start.\n\nWhat you do not do\nDo not eat in a toilet or a bin room. Do not wipe your face with a cleaning cloth. Do not take soiled gloves into the vehicle cabin.',
    points: [
      'What waste on this site must not be picked up by hand?',
      'Where is the first aid kit and the nearest running water?',
      'When do you change gloves?',
      'What do you do if you are splashed while cleaning?',
      'What do you do if you find a needle and you have no sharps container?',
    ],
  },
  {
    code: 'PLANT',
    title: 'Safe plant and equipment',
    durationMins: 15,
    sortOrder: 7,
    imageUrl: img('mower.png'),
    brief: 'Mowers, blowers, edgers, pressure washers and other plant injure people when a guard is missing, a person has not been trained, or someone reaches in while the machine is still moving.\n\nBefore you start\nCheck the guard is on and fixed. Check the lead, the plug and the controls. Check the blade or cord is not damaged. Check fuel is not leaking. Look at the ground for stones, wire, bottles and hidden sprinkler heads. If a guard is missing, do not use the machine. Tag it out and tell your supervisor.\n\nWho may use it\nIf you have not been shown how to use that machine, you do not use it. Watching someone else is not training. Do not lend plant to a client, a contractor or a new starter who is not authorised.\n\nWhile it is running\nKeep other people and animals outside the throw zone. A mower throws stones a long way. Point a blower away from people, traffic and doorways. Do not defeat a safety switch. Do not remove a guard to get the job done faster.\n\nClearing a jam\nStop the machine. Switch it off and unplug it, or remove the key, and wait until every part has stopped. Then clear the jam. Many cuts happen because the blade was still spinning.\n\nIf it is damaged\nTag it, take it out of use, and tell your supervisor before the next person picks it up. Do not tape a guard on. Do not keep using a machine with a cracked housing, a sparking lead, or a blade that is bent.',
    points: [
      'Which machines are in use today, and who is allowed to use them?',
      'What do you check before you start a machine?',
      'How do you clear a jam?',
      'How do you take a damaged machine out of use?',
      'Where is the throw zone, and who might walk into it?',
    ],
  },
  {
    code: 'SWMS',
    title: 'Safe work method statements',
    durationMins: 15,
    sortOrder: 8,
    imageUrl: img('signage.png'),
    brief: 'A safe work method statement sets out the high-risk steps of a job and the controls you must use. You read it before you start, not after something goes wrong. This talk is the script for that conversation with the crew.\n\nWhen a statement is required\nA statement is required for high risk construction work. On our jobs that includes work where a person could fall more than 2 metres, such as roofs, gutters and ladders at height. It includes work that may disturb asbestos, work on or near energised electrical services, work on or near a road that traffic is using, and work near moving plant. If you are not sure whether today\'s job needs a statement, ask before you unload the vehicle.\n\nWhat the statement must contain\nIt names the high risk work. It names the hazards and the risks, not a general warning to be careful. It describes the controls and how they will be used, watched and changed if they are not working. It is written so the crew can understand it. A statement that says "use PPE" and nothing else is not good enough for a roof, a road or a machine.\n\nBefore you start\nGet the statement for this job, not a statement from another site. Read the steps you will actually do today. If you do not understand a control, ask for it to be explained. You are expected to ask. Walk the job and compare it with the statement: access, weather, surface, plant, other people, and what is underneath the work.\n\nFollow the method\nUse the controls in the statement. That may be edge protection, a harness and anchor, exclusion of people below, a spotter near traffic, or a different machine. Do not swap in your own method because it is faster. Do not invent a new method on the roof, the road or beside a machine.\n\nWhen you stop\nStop if the site, the weather or the equipment is different from the statement. Rain on a metal roof, a missing anchor, a skylight that was not on the plan, a public path that is now open, or a machine that is not the one named. Tell your supervisor. The statement is revised before work starts again. You do not "just be careful" in the meantime.\n\nSigning\nSigning means you were consulted and you understand the controls. It does not mean you accept an unsafe job, and it does not shift the duty off the business. If a control cannot be used, do not sign and start. Say so.\n\nWhere it is kept\nThe statement is kept where the crew can read it while the work is done. Know whether that is in the vehicle, on the phone, or with the supervisor. If you cannot find it, you do not start the high risk work.',
    points: [
      'Which safe work method applies to today\'s job, and where is it kept?',
      'Which steps today are high risk, and what control does the statement name?',
      'What on this site is different from the statement?',
      'What would make you stop and ask for the method to be changed?',
      'What does signing the statement mean, and what does it not mean?',
    ],
  },
  {
    code: 'WHSLAW',
    title: 'WHS duties',
    durationMins: 15,
    sortOrder: 9,
    imageUrl: gateway('whs-responsibilities.png'),
    brief: 'Work health and safety law sets duties on the business and on you. This talk is about what that means on a cleaning or grounds job, not about a courtroom.\n\nWhat the business must do\nThe person conducting the business must provide and maintain a safe workplace, safe plant, safe systems of work, information, training and supervision. That includes the vehicles, the chemicals, the machines, and the way a roof or a road job is planned. A missing guard, no training, or no safe method is a failure of that duty.\n\nWhat you must do\nYou must take reasonable care of your own health and safety, and of other people who could be affected by your work. That includes workmates, clients and the public. You must follow reasonable instructions and the safe method you have been given. You must not wilfully put anyone at risk, including by removing a guard, ignoring a wet-floor sign, or daring someone to take a shortcut.\n\nStopping unsafe work\nYou have a right to stop work that is not safe, and to raise a concern, without being punished for it. If you are told to do a job that you cannot do safely, stop and contact your supervisor. If you are still not satisfied, use the path in the workplace procedure. Leaving the job unsafe and quiet is not loyalty.\n\nReporting\nReport hazards the same day: a broken cover, a sparking lead, a roof that will not take your weight, aggression on site. Serious incidents may have to be notified to the regulator. That includes a death, a serious injury or illness, and a dangerous incident such as a fall from height, an electric shock, or a collapse, even if nobody is badly hurt. Your supervisor makes that notification. Leave the scene as it is unless you must help someone or remove an immediate danger. Do not clean up the evidence of a serious incident.\n\nOther people\nA client or a principal on a site has duties too. Their instruction does not override a safe method. If a client tells you to walk a fragile roof or to skip a control, you refuse and call your supervisor.',
    points: [
      'What are you required to do if a job cannot be done safely?',
      'How do you raise a safety concern on this site?',
      'Which incidents must be reported the same day?',
      'What do you do with the scene after a serious incident?',
      'What do you do if a client tells you to skip a control?',
    ],
  },
  {
    code: 'RISK',
    title: 'Risk management',
    durationMins: 15,
    sortOrder: 10,
    imageUrl: gateway('risk-management.png'),
    brief: 'Before you start, look for what could hurt someone. Then control it in the right order. Being careful is not a control.\n\nFind the hazard\nA hazard is something that can cause harm. On our work that is a wet floor, a moving mower, a roof edge, traffic, a chemical, a dog, a needle, electricity, heat, or a person who may become aggressive. Look at the site as it is today, not as it was last visit. Weather, other contractors and members of the public change the risk.\n\nDecide how bad it is\nAsk who could be hurt, how badly, and how likely it is. A public path under a roof job is a higher risk than an empty yard. A cracked chemical container in a closed vehicle is a higher risk than the same container in a tray, upright and closed.\n\nControls, in order\nFirst, remove the hazard if you can. Do the job from the ground instead of the roof. Next, substitute a safer way, such as a different chemical or a different machine. Then isolate people, such as barriers under a work area or around a mower. Then engineering controls, such as a guard or edge protection. Then procedures, such as a safe work method and a spotter. Personal protective equipment comes last. Gloves and a harness do not replace a safer method.\n\nIf the only control you can name is "be careful" or "watch your step", the job is not ready. Stop and speak to your supervisor.\n\nCheck the control\nA control that is not in place is not a control. Check the sign is up, the guard is on, the people are outside the area, and the harness is clipped to the anchor named in the method. If a control fails during the job, stop. Do not finish the bay and mention it later.',
    points: [
      'What is the main hazard on this site today?',
      'Who could be hurt, other than the person doing the task?',
      'What control is already in place, and is it the best one in the order?',
      'What will you do if that control cannot be used?',
      'How will you check the control is still working halfway through the job?',
    ],
  },
  {
    code: 'RTW',
    title: 'Return to work',
    durationMins: 15,
    sortOrder: 11,
    imageUrl: img('injury.png'),
    brief: 'After an injury or illness, return to work is planned. Full duties start when you have been cleared for them, not when the crew is short.\n\nSuitable duties\nSuitable duties are real work that matches the restrictions you have been given. A certificate or a return to work plan may limit lifting, climbing, driving, hours, or repetitive work. Those limits are the job. They are not a suggestion.\n\nWhat you do\nRead the restrictions before the shift, and tell the crew leader what you can and cannot do. If a task is outside those restrictions, say so before you start it. Do not swap onto a heavier job to help the crew finish. Do not skip a restriction because you feel all right this morning. Pain later in the day is a sign you have done too much, not a sign to hide it.\n\nWhat the crew does\nDo not pressure a person on suitable duties to lift, climb or stay late. Covering their restricted task is part of the plan. Mocking a restriction is not acceptable.\n\nA setback\nReport pain, swelling, or a task you could not do the same day. Tell your supervisor. Hiding it makes the injury worse and hides the hazard from the next person. If you need treatment, get it. Do not use someone else\'s medicine.\n\nWork that is not suitable\nRoofs, ladders, heavy bins, long drives and repetitive mopping are often outside a restriction. If the only work today is that work, you do not do it. Call your supervisor and follow the plan.',
    points: [
      'Who do you tell if a task is outside your restrictions?',
      'What suitable duties are available on this site?',
      'Which tasks today would breach a lifting, climbing or driving limit?',
      'Why is a setback reported the same day?',
      'What do you do if the only work left is outside the plan?',
    ],
  },
  {
    code: 'DRIVING',
    title: 'Safe driving',
    durationMins: 15,
    sortOrder: 12,
    imageUrl: img('traffic.png'),
    brief: 'The drive between sites is part of the job. Most of the serious harm in this work happens on the road, not with a mop.\n\nBefore you leave\nYou are fit to drive: not impaired by alcohol, drugs, medicine or fatigue. Check tyres, lights, mirrors and that nothing is leaking under the vehicle. Check the load is secured and the rear vision is clear. Wear a seatbelt, and make sure every passenger does. Know the route. A full fuel card and a charged phone matter on an early start.\n\nOn the road\nDo not use a hand-held phone. Set navigation before you move. Do not rush because the last site ran late. The speed limit and the conditions decide the speed, not the next booking. Leave a gap. In rain, on a rural road, or with a heavy load, slow down.\n\nIf you are fatigued\nStop in a safe place and call your supervisor. Do not keep driving to "get it over with".\n\nA crash or a bump\nStop if it is safe. Call 000 if anyone is hurt or if the road is blocked. Do not admit fault at the scene. Exchange names, phone numbers, registration and insurer details. Take photos of the vehicles, the road and the damage. Report it to your supervisor the same day, including a minor bump in a car park. Do not leave a car-park bump because it looks small.\n\nPassengers and clients\nOnly authorised people travel in the work vehicle. A client does not get a lift unless you have been told they may.',
    points: [
      'What do you check on the vehicle before you leave?',
      'What is the rule for phones while driving?',
      'What do you do if you are too tired to continue?',
      'What do you do after a minor bump in a car park?',
      'Who is allowed to travel in the work vehicle?',
    ],
  },
  {
    code: 'OFFSITE',
    title: 'Working at external locations',
    durationMins: 15,
    sortOrder: 13,
    imageUrl: img('working-alone.png'),
    brief: 'Work away from your usual base means you may not know the exits, the people or the hazards. Treat every external site as new until you have looked at it.\n\nCheck in and check out\nUse the method your supervisor has set: a call, a message, or a sign-in book. Do it when you arrive and when you leave. If you work alone, agree the check-in time before you start. If you miss it, your supervisor should be looking for you. Do not turn the phone off.\n\nLook before you start\nFind the address so you can tell 000 where you are, including a gate, a level or a meter room. Look for traffic, dogs, chemicals, fragile roofs, water, needles, and members of the public. Find the exits and the first aid kit if the site has one. If you are meeting a client, confirm who they are before you follow them into a closed area.\n\nWhat is not acceptable\nDo not enter a site that is dark and was meant to be open. Do not enter if someone is there who should not be there. Do not start if the roof, the yard or the access is not what you were told. Leave and call your supervisor. Do not explore a plant room, a roof or a confined space to "see if it is all right".\n\nWorking alone or with the public\nKeep the vehicle accessible. Tell someone if you move to a different part of the site. If a person is aggressive or you feel unsafe, leave. Do not argue. Call your supervisor, and call 000 if you are threatened or someone is hurt.\n\nAt the end\nCheck out. Report hazards the next crew will meet, the same day.',
    points: [
      'How do you check in and check out on this job?',
      'What is the address you would give to 000?',
      'What hazards are different from your usual site?',
      'What do you do if the site is not as you were told?',
      'What do you do if you feel unsafe with a person on site?',
    ],
  },
  {
    code: 'BULLY',
    title: 'Workplace bullying',
    durationMins: 15,
    sortOrder: 14,
    imageUrl: gateway('bullying.png'),
    brief: 'Bullying is repeated unreasonable behaviour that creates a risk to a person\'s health and safety. It is a work health and safety issue. It is not a personality clash you are expected to wear.\n\nWhat it looks like\nHumiliation, insults, exclusion from the crew, constant unjustified criticism, and setting someone up to fail. It can be in person, on the phone, or in messages. It includes a group laughing at one person, hiding their gear, or refusing to speak to them on the job. Sexual harassment and threats are separate and serious. Threats and violence are reported immediately and may need a call to 000.\n\nWhat it is not\nA single harsh comment is not bullying by itself, though it can still be unacceptable. Reasonable management is not bullying. Allocating work, setting a standard, and giving feedback on poor work are part of the job when they are fair and about the work.\n\nWhat you can do\nIf you feel safe, tell the person to stop. You do not have to do that. Report it to your supervisor or use the path in the workplace procedure. You can ask for the report to be handled without the whole crew hearing it. You must not be punished, rostered out, or mocked for raising it.\n\nIf you see it\nDo not join in. Do not laugh it off. Do not pass on the message or the photo. Tell your supervisor what you saw. A witness who stays silent leaves the person alone with it.\n\nWhat happens next\nThe report is looked at. The person who reported it is told what will happen, as far as privacy allows. If the behaviour is still happening, say so again. Leaving it unreported because you want to keep the peace does not keep anyone safe.',
    points: [
      'What is the difference between bullying and a reasonable instruction?',
      'What behaviour have you seen that would need to be reported?',
      'How do you report bullying in this workplace?',
      'What do you do if you see a workmate being targeted?',
      'What do you do if there is a threat or violence?',
    ],
  },
  {
    code: 'VEHICLE',
    title: 'Vehicle safety',
    durationMins: 15,
    sortOrder: 15,
    imageUrl: img('vehicle-load-safety.png'),
    brief: 'The work vehicle carries people, fuel, chemicals and tools. Overloading, loose gear and poor maintenance injure people on the road and when you open the doors at the site.\n\nThe load\nSecure the load so it cannot shift, leak or fall out when you brake or open a door. Heavy items low and forward. Tools not loose on a seat. A blower, mower or ladder tied down, not wedged. Do not overload the vehicle or the trailer past the limit on the plate. A load that blocks mirrors or lights is not secured, it is unsafe.\n\nChemicals and fuel\nKeep containers upright, closed and separate from food and drinking water. Do not carry fuel in the cabin. Do not carry a container that is leaking. A chemical spill in the cabin is reported, and the vehicle is not used until it has been cleaned as the safety data sheet requires.\n\nPeople\nDo not carry passengers who are not authorised. Everyone wears a seatbelt. Nobody rides in a tray or a trailer.\n\nReversing and parking\nReverse only when you can see, or when a person is guiding you and standing where you can see them, not behind the vehicle. Walk around the vehicle before you reverse on a site with children, bins or low walls. Park so you can leave forward if you can. Do not block an exit or a fire hydrant.\n\nDefects\nReport defects before the next trip. Do not drive on a bald tyre, with a warning light you do not understand, with poor brakes, or with a load that is not tied down. Tag it in the way your supervisor has set, and take another vehicle.',
    points: [
      'How is today\'s load secured?',
      'Where do chemicals and fuel sit relative to food and people?',
      'Who is allowed in the vehicle, and where must they sit?',
      'How will you reverse on this site?',
      'What defects must be reported before you drive?',
    ],
  },
  {
    code: 'CHEMICAL',
    title: 'Chemical safety',
    durationMins: 15,
    sortOrder: 16,
    imageUrl: img('chemicals-sds.png'),
    brief: 'Cleaning chemicals, pesticides, paints and fuels can harm you if you breathe them, get them on your skin or in your eyes, or swallow them. Some burn. Some catch fire. Some react if you mix them.\n\nBefore you use a product\nRead the label and the safety data sheet. The label tells you the hazard and the first aid. The safety data sheet tells you the controls, the protection, and what to do for a spill. Use the gloves, eye protection and ventilation listed there. If you have not been shown how to use that product, do not use it.\n\nDecanting and mixing\nDo not put a chemical into a drink bottle or any bottle without a label. The label must name the product, not say "cleaner". Do not mix products unless the label says you can. Mixing bleach with acids, or bleach with ammonia, can release a gas that damages your lungs. If you are not sure, do not mix.\n\nWhile you use it\nUse the strength on the label. More chemical is not a better clean. Keep the area ventilated. Keep clients, children and animals out. Do not eat or smoke with chemical on your hands. Wash your hands before you eat.\n\nStorage and transport\nStore containers closed and upright. Keep incompatible products apart as the safety data sheet says. In the vehicle, keep them out of the cabin and away from food. A leaking container is taken out of use, not stood in a tray and forgotten.\n\nSpill and first aid\nA splash on skin or in the eyes is washed with running water immediately, for the time the safety data sheet states. Then tell your supervisor. A spill into a drain is reported. Do not hose a concentrated chemical into the gutter. Use the spill method you have been shown, and only if you can do it without being splashed.\n\nWhere the sheets are\nKnow where the safety data sheets are kept for the products on this vehicle. If a product has no label and no sheet, do not use it. Quarantine it and tell your supervisor.',
    points: [
      'Which chemicals are in use today, and where are the safety data sheets?',
      'What protection does the label require?',
      'What do you do if a product is in an unlabelled bottle?',
      'Which products on this job must never be mixed?',
      'What do you do for a splash in the eyes, or a spill near a drain?',
    ],
  },
];
