enum actionType {
    ADD = "ADD",
    DUPLICATE = "DUPLICATE",
    UPDATE = "UPDATE",
    DELETE = "DELETE",
    CHANGE_STATUS = "CHANGE_STATUS",
    RESET_PASSWORD = "RESET_PASSWORD",
    SEARCH = "SEARCH",
    VIEW = "VIEW",
    IMPORT_EXCEL = "IMPORT_EXCEL",
    ADD_ITEM = "ADD_ITEM",
    UPDATE_ITEM = "UPDATE_ITEM",
    DELETE_ITEM = "DELETE_ITEM",
    CHECK_IN = "CHECK_IN",
    CHECK_OUT = "CHECK_OUT",
    CREATE_REPORT = "CREATE_REPORT",
    SHIFT_MANAGEMENT = "SHIFT_MANAGER",
    VIEW_LOG = "VIEW_LOG",
    UPDATE_TASK="UPDATE_TASK",
    VIEW_ALL = "VIEW_ALL",
    ADD_SITE_ITEM = "ADD_SITE_ITEM",
    UPDATE_SITE_ITEM = "UPDATE_SITE_ITEM",
    DELETE_SITE_ITEM = "DELETE_SITE_ITEM",
    
}

export default actionType;