/** Fallback when API issueOptions is unavailable (keep in sync with API report-fault-issue.constants). */
export const REPORT_FAULT_ISSUE_OPTIONS = [
  { id: 'Broken Door Locks & Latches', name: 'Broken Door Locks & Latches' },
  { id: 'Broken Grab Rails / Accessible Fixtures', name: 'Broken Grab Rails / Accessible Fixtures' },
  { id: 'Door Won\'t Open / Stuck Shut', name: 'Door Won\'t Open / Stuck Shut' },
  { id: 'Faulty Flush Mechanisms', name: 'Faulty Flush Mechanisms' },
  { id: 'Graffiti', name: 'Graffiti' },
  { id: 'Light Bulb Burned Out', name: 'Light Bulb Burned Out' },
  { id: 'No Lights', name: 'No Lights' },
  { id: 'Paper Towel Dispenser Broken/Damaged', name: 'Paper Towel Dispenser Broken/Damaged' },
  { id: 'Slippery Floor / Flooding', name: 'Slippery Floor / Flooding' },
  { id: 'Soap Dispenser Broken/Damaged', name: 'Soap Dispenser Broken/Damaged' },
  { id: 'Tap or Urinal Running', name: 'Tap or Urinal Running' },
  { id: 'Toilet Blockage', name: 'Toilet Blockage' },
  { id: 'Toilet Paper Dispenser Broken/Damaged', name: 'Toilet Paper Dispenser Broken/Damaged' },
  { id: 'Urinal Blockage', name: 'Urinal Blockage' },
  { id: 'Vandalism', name: 'Vandalism' },
  { id: 'Wall Damage', name: 'Wall Damage' },
  { id: 'Water Leaks', name: 'Water Leaks' },
  { id: 'Other', name: 'Other' },
] as const;
