import urlConfig from "@app/config/site.config";
import { dateTimeFormat } from "@app/config/data.config";
import { AU_UTC_OFFSET, momentAu } from "@app/library/helpers/australianDatetime";
import moment from "moment";
import { userType } from "../../constants/statusUser";
import { EM_DASH } from "./new-reports-field-utils";

/** PDF URLs from the API are usually absolute; older rows may store `public/pdf/...` only — resolve against the API origin so links work from the admin SPA. */
export function resolveReportPdfHref(raw: unknown): string {
  const s = typeof raw === "string" ? raw.trim() : "";
  if (!s) return "";
  if (/^https?:\/\//i.test(s)) return s;
  const base = String(urlConfig.orderApiURL || "").replace(/\/+$/, "");
  const path = s.replace(/^\/+/, "");
  return path ? `${base}/${path}` : "";
}

export function getReportPdfField(row: any): string {
  const v = row?.pdfFile ?? row?.pdf_file;
  return typeof v === "string" ? v.trim() : "";
}

/** Prefer display title from site/template; then PDF filename from URL. */
export function reportPdfLinkLabel(row: any, href: string): string {
  const title = buildReportDisplayTitle(row);
  if (title && title !== "Report") return title;
  try {
    const pathOnly = href.split(/[?#]/)[0];
    const last = pathOnly.split("/").filter(Boolean).pop() || "";
    const base = decodeURIComponent(last.replace(/\.pdf$/i, ""));
    if (base) return base.replace(/-/g, " ");
  } catch {
    /* ignore */
  }
  return "PDF";
}

/** Admin uploads embed epoch ms in filenames; use when check_in predates actual submit. */
function inferSubmissionFromReportMedia(row: any): moment.Moment | null {
  const reports = row?.reports;
  if (!Array.isArray(reports)) return null;
  let maxTs = 0;
  for (const r of reports) {
    const val = String(r?.value ?? "");
    const re = /\/(\d{13})(?:-|\.)/g;
    let match: RegExpExecArray | null;
    while ((match = re.exec(val)) !== null) {
      const ts = Number(match[1]);
      if (Number.isFinite(ts) && ts > maxTs) maxTs = ts;
    }
  }
  if (maxTs <= 0) return null;
  const m = moment(maxTs);
  return m.isValid() ? m : null;
}

/** When the report was submitted — align with PDF reference time, not PDF regen / bad check_in. */
function getReportSubmittedAt(row: any): string | Date | null | undefined {
  const checkIn = row?.checkIn ?? row?.check_in ?? null;
  const createdAt = row?.createdAt ?? row?.created_at ?? null;
  const media = inferSubmissionFromReportMedia(row);

  let ref: string | Date | null = createdAt ?? checkIn;

  if (checkIn && createdAt) {
    const ci = moment(checkIn);
    const ca = moment(createdAt);
    if (ci.isValid() && ca.isValid()) {
      const forwardSkewMin = ci.diff(ca, "minutes");
      if (forwardSkewMin >= 540 && forwardSkewMin <= 660) ref = createdAt;
    }
  }

  if (media && ref) {
    const refM = moment(ref);
    if (refM.isValid()) {
      const aheadMin = media.diff(refM, "minutes");
      const behindMin = refM.diff(media, "minutes");
      if (aheadMin > 30 || behindMin > 30) ref = media.toDate();
    }
  } else if (media && !ref) {
    ref = media.toDate();
  }

  return ref;
}

export function resolveReportSubmittedDisplayMoment(row: any): moment.Moment | null {
  const t = getReportSubmittedAt(row);
  if (!t) return null;
  const checkIn = row?.checkIn ?? row?.check_in ?? null;
  const createdAt = row?.createdAt ?? row?.created_at ?? null;
  const wallClockStorage =
    checkIn &&
    createdAt &&
    Math.abs(moment(checkIn).diff(moment(createdAt), "minutes")) <= 2;
  const m = wallClockStorage
    ? moment(t).utcOffset(AU_UTC_OFFSET, true)
    : momentAu(t);
  return m && m.isValid() ? m : null;
}

export function formatReportSubmittedAt(row: any): string {
  const m = resolveReportSubmittedDisplayMoment(row);
  return m ? m.format(dateTimeFormat) : EM_DASH;
}

export const REPORT_DISPLAY_DATE = "D MMM YYYY";
export const REPORT_LIST_SEP = " · ";

export function formatReportViewDate(raw: unknown): string {
  const s = String(raw ?? "").trim();
  if (!s) return "";
  if (moment(s, "YYYY-MM-DD", true).isValid()) {
    return moment(s, "YYYY-MM-DD", true).format(REPORT_DISPLAY_DATE);
  }
  const m = moment(s);
  return m.isValid() ? m.format(REPORT_DISPLAY_DATE) : s;
}

export function formatReportViewTime(raw: unknown): string {
  const s = String(raw ?? "").trim();
  if (!s || s === "Invalid date") return "";
  const strict = moment(s, ["HH:mm:ss", "HH:mm"], true);
  if (strict.isValid()) return strict.format("HH:mm");
  const m = moment(s);
  return m.isValid() ? m.format("HH:mm") : s;
}

const AUTO_REPORT_NAME_SUFFIX = / - \d{4}-\d{2}-\d{2} \d{2}-\d{2}-\d{2}$/;
const AUTO_REPORT_NAME_PREFIX = /^New Report - \d{4}-\d{2}-\d{2}/;

function isAutoGeneratedReportInternalName(name: string): boolean {
  const s = String(name || "").trim();
  if (!s) return false;
  return AUTO_REPORT_NAME_PREFIX.test(s) || AUTO_REPORT_NAME_SUFFIX.test(s);
}

/** e.g. "Bayside Public Amenities Cleaning Report" */
export function buildReportDisplayTitle(row: {
  siteName?: string;
  serviceName?: string;
  taskName?: string;
  reportTemplate?: { name?: string };
}): string {
  const site = String(row.siteName || "").trim();
  const service = String(row.serviceName || "").trim();
  const tpl = String(row.reportTemplate?.name || "").trim();

  if (site && service) {
    let suffix = service;
    const siteLower = site.toLowerCase();
    const svcLower = service.toLowerCase();
    if (siteLower.endsWith("public amenities") && svcLower.startsWith("public amenities ")) {
      suffix = service.slice("Public Amenities ".length).trim() || service;
    } else if (svcLower.startsWith(`${siteLower} `)) {
      suffix = service.slice(site.length).trim() || service;
    }
    const base = `${site} ${suffix}`.replace(/\s+/g, " ").trim();
    return / report$/i.test(base) ? base : `${base} Report`;
  }
  if (site && tpl) {
    const base = `${site} ${tpl}`.replace(/\s+/g, " ").trim();
    return / report$/i.test(base) ? base : `${base} Report`;
  }
  if (site) {
    return / report$/i.test(site) ? site : `${site} Report`;
  }

  const legacyInternalName = String(row.taskName || "").trim();
  if (legacyInternalName && !isAutoGeneratedReportInternalName(legacyInternalName)) {
    return legacyInternalName.replace(AUTO_REPORT_NAME_SUFFIX, "").trim();
  }
  if (tpl) return tpl;
  return "Report";
}

export function formatMobileReportCardTitle(row: any): string {
  const base = buildReportDisplayTitle(row);
  const m = resolveReportSubmittedDisplayMoment(row);
  if (!m) return base;
  return `${base} ${m.format("D MMM")} ${m.format("HH:mm")}`;
}

export function formatSubmittedByRow(row: any): string {
  const staffName = String(row?.staff?.fullName || row?.staff?.username || "").trim();
  const creatorType = row?.createdUser?.type != null ? +row.createdUser.type : 0;
  const createdBy = row?.createdBy != null ? +row.createdBy : 0;
  const staffId = row?.staffId != null ? +row.staffId : 0;

  if (creatorType === userType.ADMIN || (createdBy > 0 && staffId > 0 && createdBy !== staffId)) {
    return "Admin";
  }
  return staffName || EM_DASH;
}

export function formatCustomerDisplayName(row: any): string {
  const company =
    String(row?.companyName || row?.customer?.customerInfo?.companyName || "").trim();
  const person = String(
    row?.customer?.fullName || row?.customerName || row?.customer?.username || "",
  ).trim();
  if (company) return company;
  if (person) return person;
  return EM_DASH;
}
